---
- name: Package prerequisites for Perl
  apt: name=make state=present
  with_items:
    - make
    - gcc
    - curl
    - perl-doc
    - libmodule-build-perl

- name: Install cpanminus
  shell: curl -L http://cpanmin.us | perl - App::cpanminus
  register: install_cpanm
  changed_when: "'is up to date' not in install_cpanm.stdout"

- name: Update ExtUtils::MakeMaker
  shell: cpanm ExtUtils::MakeMaker
  register: update_extutils_makemaker
  changed_when: "'is up to date' not in update_extutils_makemaker.stdout"

- name: Update File::Spec
  shell: cpanm File::Spec
  register: update_file_spec
  changed_when: "'is up to date' not in update_file_spec.stdout"

- name: Install Carton
  shell: cpanm --dev Carton --mirror https://cpan.metacpan.org/
  register: install_carton
  changed_when: "'is up to date' not in install_carton.stdout"

- name: Install URI
  shell: cpanm URI
  register: install_uri
  changed_when: "'is up to date' not in install_uri.stdout"
